export {};
interface AppInfo { id:string; name:string; version?:string; path?:string; uiType?:string; status:string; enabled:boolean; favorite?:boolean; error?:string; lastUsedAt?:string; useCount?:number; manifestIssues?:string[]; commands:{id:string;title:string}[]; hotkeys?:{combo:string;command:string}[]; permissions:string[] }
interface Bridge { getApps():Promise<AppInfo[]>; getApp(id:string):Promise<AppInfo>; action(id:string,a:string):Promise<AppInfo>; getHistory(id:string,p?:any):Promise<any>; getLogs(id:string,p?:any):Promise<any>; getSettings():Promise<any>; patchSettings(p:any):Promise<any> }
const bridge=(window as any).__management as Bridge; let apps:AppInfo[]=[]; let selected=""; let busy=false;
const $=(id:string)=>document.getElementById(id)!; const esc=(v:unknown)=>String(v??"").replace(/[&<>\"]/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]!));
function notice(text:string,error=false){const n=$("notice");n.textContent=text;n.style.background=error?"#a52b2b":"#263442";n.classList.add("show");setTimeout(()=>n.classList.remove("show"),2800)}
function renderList(){const q=($("search") as HTMLInputElement).value.trim().toLowerCase();const list=$("app-list");const visible=apps.filter(a=>`${a.name} ${a.id}`.toLowerCase().includes(q));if(!visible.length){list.innerHTML='<div class="empty">暂无匹配 App</div>';return}list.innerHTML=visible.map(a=>`<div class="app ${a.id===selected?"selected":""}" data-id="${esc(a.id)}"><div class="app-title"><span><i class="dot ${esc(a.status)}"></i>${esc(a.name)}</span><span>${a.favorite?'★':''}</span></div><div class="app-meta">${esc(a.id)} · ${esc(a.status)}${a.enabled?'':' · 已禁用'}</div></div>`).join("");list.querySelectorAll<HTMLElement>(".app").forEach(el=>el.onclick=()=>{selected=el.dataset.id!;renderList();void renderDetail()})}
function actionButtons(a:AppInfo){const broken=a.status==='broken';const disabled=broken||!a.enabled;return `<button data-action="${a.status==='running'?'stop':'start'}" ${disabled&&a.status!=='running'?'disabled':''}>${a.status==='running'?'停止':'启动'}</button><button data-action="reload" ${disabled?'disabled':''}>重载</button><button data-action="${a.enabled?'disable':'enable'}" class="${a.enabled?'danger':'primary'}" ${broken?'disabled':''}>${a.enabled?'禁用':'启用'}</button><button data-action="${a.favorite?'unfavorite':'favorite'}" ${broken?'disabled':''}>${a.favorite?'取消收藏':'收藏'}</button>`}
async function renderDetail(){const view=$("view-apps");if(!selected){view.innerHTML='<div class="state">选择一个 App 查看详情</div>';return}view.innerHTML='<div class="state">正在加载详情…</div>';try{const a=await bridge.getApp(selected);view.innerHTML=`<div class="toolbar"><div><h2 class="title">${esc(a.name)}</h2><div class="muted">${esc(a.id)} · ${esc(a.version)} · ${esc(a.status)}</div></div><div class="actions">${actionButtons(a)}</div></div>${a.error?`<div class="error">清单错误：${esc(a.error)}</div>`:''}${a.manifestIssues?.length?`<div class="error">构建问题：${a.manifestIssues.map(esc).join('<br>')}</div>`:''}<div class="cards"><div class="card"><h2>基本信息</h2><div class="row"><span class="label">目录</span><span class="code">${esc(a.path||'')}</span></div><div class="row"><span class="label">UI 类型</span><span>${esc(a.uiType||'none')}</span></div><div class="row"><span class="label">使用次数</span><span>${a.useCount??0}</span></div><div class="row"><span class="label">最近使用</span><span>${esc(a.lastUsedAt||'暂无')}</span></div></div><div class="card"><h2>权限声明</h2>${a.permissions.length?a.permissions.map(p=>`<span class="permission ${/^(screen|mouse|process)\./.test(p)?'':'unknown'}">${esc(p)}</span>`).join(''):'<div class="muted">未声明</div>'}<p class="muted">这是本地 App 的能力声明，当前版本不强制拦截 host.*；只运行可信代码。</p></div><div class="card"><h2>命令与热键</h2>${a.commands.length?a.commands.map(c=>`<div class="row"><span>${esc(c.title)}</span><span class="code">${esc(a.hotkeys?.find(h=>h.command===c.id)?.combo||'')}</span></div>`).join(''):'<div class="muted">暂无命令</div>'}</div><div class="card"><h2>运行记录与日志</h2><div class="actions"><button id="history">查看历史</button><button id="logs">查看日志</button></div><div id="subview"></div></div></div>`;view.querySelectorAll<HTMLButtonElement>('[data-action]').forEach(b=>b.onclick=()=>void doAction(b.dataset.action!));$("history").onclick=()=>void showHistory();$("logs").onclick=()=>void showLogs()}catch(e){view.innerHTML=`<div class="error">详情加载失败：${esc((e as Error).message)}</div>`}}
async function doAction(action:string){if(busy)return;busy=true;notice("正在执行…");try{await bridge.action(selected,action);notice("操作已完成");await load()}catch(e){notice(`操作失败：${(e as Error).message}`,true)}finally{busy=false}}
async function load(){try{apps=await bridge.getApps();if(selected&&!apps.some(a=>a.id===selected))selected="";if(!selected&&apps[0])selected=apps[0].id;renderList();await renderDetail()}catch(e){$("app-list").innerHTML=`<div class="error">加载失败：${esc((e as Error).message)}</div>`;$("view-apps").innerHTML='<div class="state">无法加载 App 列表</div>'}}
async function showHistory(){const box=$("subview");box.innerHTML='<div class="muted">正在加载历史…</div>';try{const data=await bridge.getHistory(selected,{limit:30});box.innerHTML=data.events?.length?`<div class="logbox">${data.events.map((e:any)=>esc(`${e.at} ${e.kind} ${e.outcome}${e.command?' '+e.command:''}${e.message?' '+e.message:''}`)).join('\n')}</div>`:'<div class="empty">暂无历史</div>'}catch(e){box.innerHTML=`<div class="error">历史读取失败：${esc((e as Error).message)}</div>`}}
async function showLogs(){const box=$("subview");box.innerHTML='<div class="muted">正在加载日志…</div>';try{const data=await bridge.getLogs(selected,{limit:100});box.innerHTML=data.lines?.length?`<div class="logbox">${data.lines.map(esc).join('\n')}</div>`:'<div class="empty">暂无日志</div>'}catch(e){box.innerHTML=`<div class="error">日志读取失败：${esc((e as Error).message)}</div>`}}
async function showSettings(){const view=$("view-settings");view.innerHTML='<div class="state">正在加载设置…</div>';try{const s=await bridge.getSettings();view.innerHTML=`<h2 class="title">Host 设置</h2><p class="muted">设置仅影响宿主，不会修改 App 清单。</p><div class="card"><label class="field"><span>Launcher 热键</span><input id="hotkey" value="${esc(s.launcherHotkey)}"></label><label class="field"><span>日志保留天数</span><input id="days" type="number" min="1" max="365" value="${s.logRetentionDays}"></label><label class="field"><span>每个 App 最大日志容量</span><input id="bytes" type="number" min="1024" value="${s.maxLogBytesPerApp}"></label><p><button class="primary" id="save">保存设置</button></p></div>`;$("save").onclick=async()=>{try{await bridge.patchSettings({launcherHotkey:($("hotkey") as HTMLInputElement).value,logRetentionDays:Number(($('days') as HTMLInputElement).value),maxLogBytesPerApp:Number(($('bytes') as HTMLInputElement).value)});notice('设置已保存')}catch(e){notice(`保存失败：${(e as Error).message}`,true)}}}catch(e){view.innerHTML=`<div class="error">设置加载失败：${esc((e as Error).message)}</div>`}}
$("search").addEventListener("input",renderList);document.querySelectorAll<HTMLButtonElement>(".tab").forEach(tab=>tab.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));tab.classList.add("active");const appsView=tab.dataset.view==='apps';$("main-layout").classList.toggle("settings-mode",!appsView);$("sidebar").classList.toggle("hidden",!appsView);$("view-apps").classList.toggle("hidden",!appsView);$("view-settings").classList.toggle("hidden",appsView);if(!appsView)void showSettings()});void load();
